[astra]
requires-astra = ">=0.6.3"

[project]
name = "FlowType_K"
version = "0.1.0"
author = "Korarei"
requires-aviutl2 = "2004700"

[build]
[[build.plugins]]
id = "core"
shell = "pwsh"
variables = { SOURCE = "./plugins" }

[build.plugins.release]
commands = '''
$dst = "$env:BUILD_DIRECTORY/Release"
cmake -S "$env:SOURCE" -B "$dst" --preset release -DREQUIRES_AVIUTL2="$env:PROJECT_REQUIRES_AVIUTL2" -DVERSION="$env:PROJECT_VERSION"
cp "$dst/compile_commands.json" "$env:SOURCE"
cmake --build "$dst"
'''
artifacts = ["${BUILD_DIRECTORY}/Release/*.aux2"]

[build.plugins.debug]
commands = '''
$dst = "$env:BUILD_DIRECTORY/Debug"
cmake -S "$env:SOURCE" -B "$dst" --preset debug -DREQUIRES_AVIUTL2="$env:PROJECT_REQUIRES_AVIUTL2"
cp "$dst/compile_commands.json" "$env:SOURCE"
cmake --build "$dst"
'''
artifacts = ["${BUILD_DIRECTORY}/Debug/*.aux2"]

[[build.scripts]]
id = "typography"
prefix = "@"
suffix = ".anm2"
variables = { SOURCE = "./scripts/typography", LABEL = "Text" }
include-directories = ["${SOURCE}/shaders"]
sources = [
    { file = "${SOURCE}/motion.lua" },
    { file = "${SOURCE}/island.lua" },
    { file = "${SOURCE}/kerning.lua" },
    { file = "${SOURCE}/trim.lua" },
    { file = "${SOURCE}/blink.lua" },
    { file = "${SOURCE}/echo.lua" },
]

[release]
[release.package]
information = "${PROJECT_NAME} v${PROJECT_VERSION} by ${PROJECT_AUTHOR}"
license = "MIT"
website = "https://github.com/korarei/AviUtl2_FlowType_K_Script"
report-issue = "https://github.com/korarei/AviUtl2_FlowType_K_Script/issues"
summary = "AviUtl ExEdit2向けテキストアニメーション作成支援ツール"
description = """
以下の機能が追加される

アニメーション効果

- Text\\Motion@FlowType_K: 全自動リリックモーション
- Text\\Island@FlowType_K: パーツ分解
- Text\\Kerning@FlowType_K: 全自動カーニング
- Text\\Trim@FlowType_K: 余白除去
- Text\\Deform@FlowType_K: 変形
- Text\\Align@FlowType_K: 整列
- Text\\Transform@FlowType_K: 座標変換
- Text\\Blink@FlowType_K: 点滅
- Text\\Echo@FlowType_K: 残像

オブジェクトメニュー (オブジェクトを右クリック)

- FlowType_K\\テキストを文字ごとに分解: テキスト分解

プロパティメニュー (オブジェクト設定項目を右クリック)

- FlowType_K\\値を揃える\\全ての区間: 現在値を全ての区間にコピー
- FlowType_K\\値を揃える\\以前の区間: 現在値を以前の区間にコピー
- FlowType_K\\値を揃える\\以降の区間: 現在値を以降の区間にコピー
- FlowType_K\\値を反転\\現在の区間: 現在値を反転 (符号，ON/Off)
- FlowType_K\\値を反転\\全ての区間: 全ての区間の値を反転 (符号，ON/Off)
- FlowType_K\\値を反転\\以前の区間: 以前の区間の値を反転 (符号，ON/Off)
- FlowType_K\\値を反転\\以降の区間: 以降の区間の値を反転 (符号，ON/Off)

- FlowType_K\\エフェクトをコピー\\エイリアス形式 (INI 形式): エフェクトをエイリアス形式でクリップボードへコピー
- FlowType_K\\エフェクトをコピー\\FlowType_K 形式 (TOML 形式): エフェクトを FlowType_K 形式でクリップボードへコピー
"""

[[release.contents.extensions]]
directory = "Plugin/${PROJECT_NAME}"
files = ["plugin:core"]

[[release.contents.extensions]]
directory = "Script/${PROJECT_NAME}"
files = ["script:typography"]

[[release.contents.extensions]]
directory = "Preset/"
files = ["./presets/*.preset"]

[[release.contents.documents]]
directory = "Script/${PROJECT_NAME}"
files = ["./*.md", "./LICENSE"]
